import { clamp } from '../../utils/math.js';

export function getSmoothingOptions(dom) {
  const inputs = dom.inputs;
  return {
    smoothingMode: inputs.smoothingModeInput.value,
    radius: clamp(parseInt(inputs.radiusRange.value, 10) || 3, 1, 12),
    sigmaColor: clamp(parseInt(inputs.sigmaColorRange.value, 10) || 30, 1, 200),
    sigmaSpace: 4,
    quant: 0,
    lumaPreserve: clamp(parseInt(inputs.lumaPreserveRange.value, 10) || 85, 0, 100) / 100,
    chromaSmooth: clamp(parseInt(inputs.chromaSmoothRange.value, 10) || 0, 0, 100) / 100,
    chromaSmoothA: clamp(parseInt(inputs.chromaSmoothARange.value, 10) || 100, 0, 100) / 100,
    chromaSmoothB: clamp(parseInt(inputs.chromaSmoothBRange.value, 10) || 100, 0, 100) / 100,
    chromaRadius: clamp(parseInt(inputs.chromaRadiusRange.value, 10) || 2, 1, 8),
    chromaSigmaSpace: clamp(parseFloat(inputs.chromaSigmaSpaceRange.value) || 3, 0.5, 12),
    chromaSigmaColor: clamp(parseInt(inputs.chromaSigmaColorRange.value, 10) || 26, 1, 80),
    chromaClamp: clamp(parseInt(inputs.chromaClampRange.value, 10) || 0, 0, 100) / 100,
    neutralProtect: clamp(parseInt(inputs.neutralProtectRange.value, 10) || 0, 0, 100) / 100,
    lumaProtect: clamp(parseInt(inputs.lumaProtectRange.value, 10) || 0, 0, 100) / 100,
    adaptiveChroma: clamp(parseInt(inputs.adaptiveChromaRange.value, 10) || 0, 0, 100) / 100,
    protectSkin: !!inputs.protectSkinInput.checked,
    artifactBoost: clamp(parseInt(inputs.artifactBoostRange.value, 10) || 0, 0, 100) / 100,
    previewMode: inputs.previewModeInput.value,
    previewSplit: clamp(parseInt(inputs.previewSplitRange.value, 10) || 50, 0, 100) / 100,
    paletteLevels: clamp(parseInt(inputs.paletteLevelsRange.value, 10) || 0, 0, 32),
    neighborMerge: clamp(parseInt(inputs.neighborMergeRange.value, 10) || 0, 0, 100) / 100,
    edgeDetect: !!inputs.edgeDetectInput.checked,
    edgeOverlay: !!inputs.edgeOverlayInput.checked,
    outlineOverlay: !!inputs.outlineOverlayInput.checked,
    edgeKernel: inputs.edgeKernelInput.value || 'sobel',
    edgeSensitivity: clamp(parseInt(inputs.edgeSensitivityRange.value, 10) || 50, 0, 100) / 100,
    edgeThreshold: clamp(parseInt(inputs.edgeThresholdRange.value, 10) || 30, 0, 100) / 100,
    edgePreblur: clamp(parseInt(inputs.edgePreblurRange.value, 10) || 1, 0, 3),
    edgeInfluence: clamp(parseInt(inputs.edgeInfluenceRange.value, 10) || 1, 0, 6),
    edgeFalloff: inputs.edgeFalloffInput.value || 'linear',
    edgeOverlayMode: inputs.edgeOverlayModeInput.value || 'both',
    edgeOverlayOpacity: clamp(parseInt(inputs.edgeOverlayOpacityRange.value, 10) || 70, 0, 100) / 100,
    edgeView: inputs.edgeViewInput.value || 'result',
    outlineMode: inputs.outlineModeInput.value || 'weighted',
    outlineThreshold: clamp(parseInt(inputs.outlineThresholdRange.value, 10) || 30, 0, 100) / 100,
    outlineThickness: clamp(parseInt(inputs.outlineThicknessRange.value, 10) || 1, 1, 6),
    outlineThin: !!inputs.outlineThinInput.checked,
    outlineColor: inputs.outlineColorInput.value || 'black',
    outlineMerge: !!inputs.outlineMergeInput.checked,
    outlineMergeStrength: clamp(parseInt(inputs.outlineMergeStrengthRange.value, 10) || 40, 0, 100) / 100,
    outlineBlendMode: inputs.outlineBlendModeInput.value || 'multiply',
    edgePreserve: clamp(parseInt(inputs.edgeStrengthRange.value, 10) || 0, 0, 100) / 100,
    edgeSmooth: clamp(parseInt(inputs.edgeSmoothRange.value, 10) || 0, 0, 3),
    edgeSoften: clamp(parseInt(inputs.edgeSoftenRange.value, 10) || 0, 0, 100) / 100
  };
}
